/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_java_util_MemoryUtils */

#ifndef _Included_main_java_util_MemoryUtils
#define _Included_main_java_util_MemoryUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     main_java_util_MemoryUtils
 * Method:    openBuffer
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_main_java_util_MemoryUtils_openBuffer
  (JNIEnv *, jclass);

/*
 * Class:     main_java_util_MemoryUtils
 * Method:    mapBuffer
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_main_java_util_MemoryUtils_mapBuffer
  (JNIEnv *, jclass);

/*
 * Class:     main_java_util_MemoryUtils
 * Method:    unmapBuffer
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_main_java_util_MemoryUtils_unmapBuffer
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
