/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fmcb_Register */

#ifndef _Included_fmcb_Register
#define _Included_fmcb_Register
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fmcb_Register
 * Method:    initialize
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_fmcb_Register_initialize
  (JNIEnv *, jclass, jstring);

/*
 * Class:     fmcb_Register
 * Method:    request
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_fmcb_Register_request
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
