/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fmcb_memory_Memory */

#ifndef _Included_fmcb_memory_Memory
#define _Included_fmcb_memory_Memory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fmcb_memory_Memory
 * Method:    openBuffer
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_fmcb_memory_Memory_openBuffer
  (JNIEnv *, jclass);

/*
 * Class:     fmcb_memory_Memory
 * Method:    mapBuffer
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_fmcb_memory_Memory_mapBuffer
  (JNIEnv *, jclass);

/*
 * Class:     fmcb_memory_Memory
 * Method:    unmapBuffer
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_fmcb_memory_Memory_unmapBuffer
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
